// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riefbexhwazkcnlpxmyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZWZiZXhod2F6a2NubHB4bXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTczNDIsImV4cCI6MjA2MzI3MzM0Mn0.b8jqy4Sz6WzpalFXO-DWIsXIQ_2OSHPYMpBdtjJcwNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);